BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test" or "only_test"
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 30
  LR: 3e-4
  MODEL_FILE_NAME: PURE_UBFC_RhythmMamba
  AUG: 1
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: True               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/mnt/e/Vscode/Rhythm Mamba/RhythmMamba/rhythm-mamba-clean/Data/PURE/"          # Raw dataset path, need to be updated
    CACHED_PATH: "./dataset/PURE/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8  # Use 80% for training
    PREPROCESS :
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: True                 # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/mnt/e/Vscode/Rhythm Mamba/RhythmMamba/rhythm-mamba-clean/Data/PURE/"          # Raw dataset path, need to be updated
    CACHED_PATH: "./dataset/PURE/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0  # Use 20% for validation
    PREPROCESS :
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: UBFC  # Changed from UBFC-rPPG to UBFC to match loader
    DO_PREPROCESS: True                 # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/mnt/e/Vscode/Rhythm Mamba/RhythmMamba/rhythm-mamba-clean/Data/DATASET_2"          # Raw dataset path, need to be updated
    CACHED_PATH: "./dataset/UBFC/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0  # Use 100% for testing (cross-dataset testing)
    PREPROCESS :
      DATA_TYPE: ['Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: RhythmMamba
  MODEL_DIR: ""
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""
